In [5]:
import pandas as pd
import seaborn as sns
import warnings
import os
import sys

warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

In [6]:
sys.path.insert(0, os.path.abspath('../src'))

from training import load_data

ImportError: cannot import name 'load_data' from 'training' (c:\Users\Nicole Passi\Desktop\Proyecto data\Defunciones_Euskadi_ML\src\training.py)

In [ ]:
defunciones = pd.read_csv("../data/def_euskadi.csv", encoding='ISO-8859-1', skiprows=1)

In [ ]:
defunciones

,grandes grupos CIE-10,mes,tramo edad cumplida,sexo,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,I. Ciertas enfermedades infecciosas y parasita...,Enero,0,Hombres,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,I. Ciertas enfermedades infecciosas y parasita...,Enero,0,Mujeres,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,I. Ciertas enfermedades infecciosas y parasita...,Enero,1 - 9,Hombres,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,I. Ciertas enfermedades infecciosas y parasita...,Enero,1 - 9,Mujeres,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,I. Ciertas enfermedades infecciosas y parasita...,Enero,10 - 19,Hombres,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5539,Covid-19 Probable,Diciembre,70 - 79,Mujeres,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5540,Covid-19 Probable,Diciembre,80 - 89,Hombres,0,0,0,0,0,0,0,0,0,0,2,0,0,0
5541,Covid-19 Probable,Diciembre,80 - 89,Mujeres,0,0,0,0,0,0,0,0,0,0,3,1,0,0
5542,Covid-19 Probable,Diciembre,>= 90,Hombres,0,0,0,0,0,0,0,0,0,0,3,0,1,0
5543,Covid-19 Probable,Diciembre,>= 90,Mujeres,0,0,0,0,0,0,0,0,0,0,1,1,0,0

In [ ]:
defunciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5544 entries, 0 to 5543
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   grandes grupos CIE-10  5544 non-null   object
 1   mes                    5544 non-null   object
 2   tramo edad cumplida    5544 non-null   object
 3   sexo                   5544 non-null   object
 4   2010                   5544 non-null   int64
 5   2011                   5544 non-null   int64
 6   2012                   5544 non-null   int64
 7   2013                   5544 non-null   int64
 8   2014                   5544 non-null   int64
 9   2015                   5544 non-null   int64
 10  2016                   5544 non-null   int64
 11  2017                   5544 non-null   int64
 12  2018                   5544 non-null   int64
 13  2019                   5544 non-null   int64
 14  2020                   5544 non-null   int64
 15  2021                   5544 non-null   int64
 16  2022                   5544 non-null   int64
 17  2023                   5544 non-null   int64
dtypes: int64(14), object(4)
memory usage: 779.8+ KB

In [ ]:
defunciones.describe()

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
count,5544.000000,5544.000000,5544.000000,5544.000000,5544.000000,5544.000000,5544.000000,5544.000000,5544.000000,5544.000000,5544.000000,5544.000000,5544.000000,5544.000000
mean,3.491522,3.577201,3.658189,3.551948,3.635823,3.879690,3.828102,3.901876,3.922439,3.888889,4.373557,4.161797,4.363997,4.024351
std,12.365091,12.585188,12.872691,12.304755,12.610656,13.450457,13.172082,13.614209,13.466904,13.193255,14.351276,13.355503,13.521870,13.091276
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.250000,1.000000
max,153.000000,154.000000,153.000000,130.000000,143.000000,150.000000,144.000000,173.000000,147.000000,145.000000,213.000000,188.000000,159.000000,172.000000

In [ ]:
defunciones.dtypes

grandes grupos CIE-10    object
mes                      object
tramo edad cumplida      object
sexo                     object
2010                      int64
2011                      int64
2012                      int64
2013                      int64
2014                      int64
2015                      int64
2016                      int64
2017                      int64
2018                      int64
2019                      int64
2020                      int64
2021                      int64
2022                      int64
2023                      int64
dtype: object

In [ ]:
#pasar de meses a nÃºmeros
meses_num = { 
    'Enero': 1,
    'Febrero': 2,
    'Marzo': 3,
    'Abril': 4,
    'Mayo': 5,
    'Junio': 6,
    'Julio': 7,
    'Agosto': 8,
    'Septiembre': 9,
    'Octubre': 10,
    'Noviembre': 11,
    'Diciembre': 12
}
defunciones['mes'] = defunciones['mes'].map(meses_num)

In [ ]:
#pasar de enfermedades a nÃºmeros
enfermedades = {
    'I. Ciertas enfermedades infecciosas y parasitarias (A00 - B99)': 1,
    'II. Tumores [neoplasias] (C00 - D48)': 2,
    'III. Enferm. sangre y Ã³rganos hematop., ciertos trast. inmunidad (D50-D89)': 3,
    'IV. Enfermedades endocrinas, nutricionales y metabÃ³licas (E00 - E90)': 4,
    'V. Trastornos mentales y del comportamiento (F00 - F99)': 5,
    'VI. Enfermedades del sistema nervioso (G00 - G99)': 6,
    'VII. Enfermedades del ojo y sus anexos (H00 - H59)': 7,
    'VIII. Enfermedades del oÃ­do y de la apÃ³fisis mastoides (H60 - H95)': 8,
    'IX. Enfermedades del sistema circulatorio (I00 - I99)': 9,
    'X. Enfermedades del sistema respiratorio (J00 - J99)': 10,
    'XI. Enfermedades del sistema digestivo (K00 - K93)': 11,
    'XII. Enfermedades de la piel y del tejido subcutÃ¡neo (L00 - L99)': 12,
    'XIII. Enfermedades sistema osteomuscular y tejido conjuntivo (M00 - M99)': 13,
    'XIV. Enfermedades del sistema genitourinario (N00 - N99)': 14,
    'XV. Embarazo, parto y puerperio (O00 - O99)': 15,
    'XVI. Ciertas afecciones originadas en el perÃ­odo perinatal (P00 - P96)': 16,
    'XVII. Malformaciones congÃ©n., deformidades y anomalÃ­as cromos. (Q00 - Q99)': 17,
    'XVIII. SÃ­ntomas, signos y hallazgos anormales clÃ­nicos y labor. (R00 - R99)': 18,
    'XX. Causas externas de mortalidad (V01 - Y89)': 19,
    'Covid-19 Confirmado': 20,
    'Covid-19 Probable': 21
}

defunciones['grandes grupos CIE-10'] = defunciones['grandes grupos CIE-10'].map(enfermedades)

In [ ]:
#pasar de tramo edad a nÃºmeros
edad_a_numeros = {
    '0': 1,
    '1 - 9': 2,
    '10 - 19': 3,
    '20 - 29': 4,
    '30 - 39': 5,
    '40 - 49': 6,
    '50 - 59': 7,
    '60 - 69': 8,
    '70 - 79': 9,
    '80 - 89': 10,
    '>= 90': 11
}

defunciones['tramo edad cumplida'] = defunciones['tramo edad cumplida'].map(edad_a_numeros)

In [ ]:
#pasar sexo a nÃºmero
sexo_num = {'Hombres': 0, 'Mujeres': 1}
defunciones['sexo'] = defunciones['sexo'].map(sexo_num)

In [ ]:
defunciones[['tramo edad cumplida', 'mes', 'grandes grupos CIE-10', 'sexo']].head()

   tramo edad cumplida  mes  grandes grupos CIE-10  sexo
0                    1    1                      1     0
1                    1    1                      1     1
2                    2    1                      1     0
3                    2    1                      1     1
4                    3    1                      1     0

In [ ]:
# Crear columnas por rango de aÃ±os
defunciones['rango1'] = defunciones[['2010', '2011', '2012', '2013', '2014']].sum(axis=1)

defunciones['rango2'] = defunciones[['2015', '2016', '2017', '2018', '2019']].sum(axis=1)

defunciones['rango3'] = defunciones[['2020', '2021', '2022', '2023']].sum(axis=1)

In [ ]:
defunciones

,grandes grupos CIE-10,mes,tramo edad cumplida,sexo,2010,2011,2012,2013,2014,2015,...,2017,2018,2019,2020,2021,2022,2023,rango1,rango2,rango3
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,2,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,1,1,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5539,21,12,9,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5540,21,12,10,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,2
5541,21,12,10,1,0,0,0,0,0,0,...,0,0,0,3,1,0,0,0,0,4
5542,21,12,11,0,0,0,0,0,0,0,...,0,0,0,3,0,1,0,0,0,4
5543,21,12,11,1,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,2